// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral() // Consider replacing jcenter() with mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2' // Ensure this is up to date
        classpath 'com.google.gms:google-services:4.4.2' // Ensure this is up to date
    }
}


allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url = 'https://jitpack.io' }
        flatDir {
            dirs 'libs'
        }
        mavenCentral() {
            content {
                includeModule("com.theartofdev.edmodo", "android-image-cropper")
            }
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
